# Basic Information 
title: Iris Xia
position: Master Student
affiliation: Yale University
email: iris.xia@yale.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
title: "Iris Xia | Yale"
description: "Iris Xia, 2nd year Master's student in Computer Science at Yale University. Research in computer vision, depth estimation, fairness-aware optimization, and medical AI."
keywords: "Iris Xia, Yale, Computer Vision, Depth Estimation, AI Research, Machine Learning"
url: "https://barricature.github.io"   # base URL of your site
canonical: "https://barricature.github.io/"

# Links 
# If you don't need one of them, you may delete the corresponding line.
# google_scholar: https://scholar.google.com/
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/Barricature
linkedin: https://www.linkedin.com/in/iris-yuhong-xia/
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/iris_profile.jpg
favicon: .assets/img/favicon-32x32.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: G-D49V4DS47G

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
